### ISSUE TITLE
Is it possible to load images using template expressions?

### ISSUE THREAD

**Issue by edanweis** [emaphp/handlebars-template-loader#12]
I can't seem to include template expressions with image processing. So that: 

`<img src="images/{{nice-guy}}">` 

becomes

`<img src="require('images/emmanuel.jpg')">`

Eg: this is done in [handlebars-loader](https://github.com/pcardune/handlebars-loader) using inlineRequires option.

> inlineRequires: Defines a regex that identifies strings within helper/partial parameters that should be replaced by inline require statements.

It would be nice to be able to chain loaders with this option, or specify other parameters so we can get something like: `require('image-webpack!./images/emmanuel.jpg')` to use with other loaders such as [resize-image-loader](https://github.com/Levelmoney/resize-image-loader).

**Comment by emaphp** [comment]
I had to implement a similar in underscore-template-loader, so yeah, it's something that I will eventually add. Not sure how much time will demand though. I'll take a look at it.

**Comment by emaphp** [comment]
Update: I updated the package a few days ago. Now the loader checks if an attribute contains a template expression before inserting the require string. If a template expression is found then that value is leaved unaltered. This allows the user to use a hbs expression inside an attribute. Still, user need to keep in mind that these routes are not relative to the template itself. Example:

``` html
<!-- Static path - Relative to this template -->
<img src="../img/dog.png" alt="dog"/>

<!-- Dynamic route - Relative to index -->
<img src="img/{{catImg}}" alt="cat" />
```

No regex option was added because I considered it was kind of redundant. Chaining loaders still not supported though, we'll see if it can be done in the future. You'll need to define special rules in your webpack configuration file.
